/*
 * Catálogo verificado exclusivamente con fuentes oficiales de ISTQB.
 * Fecha de revisión: 2026-08-20.
 *
 * Todas las certificaciones abren `pdfUrl` en istqb.org. No se conserva
 * ninguna copia local de los syllabi dentro de este proyecto.
 */

window.ISTQB_PORTFOLIO = {
  verifiedOn: "2026-08-20",
  officialPortfolioUrl: "https://istqb.org/what-we-do/",
  officialCertificationsUrl: "https://istqb.org/certifications/",
  officialWheelUrl: "https://istqb.org/wp-content/uploads/2026/05/050526_Portfolio-Export-1.png",
  groups: [
    {
      id: "foundation",
      title: "Foundation",
      subtitle: "El punto de partida",
      color: "#143A61",
      certifications: [
        {
          id: "ctfl",
          wheelLabel: "Foundation",
          name: "Certified Tester Foundation Level",
          code: "CTFL",
          version: "v4.0.1",
          publishedYear: 2024,
          pageUrl: "https://istqb.org/certifications/certified-tester-foundation-level-ctfl-v4-0/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2024/11/ISTQB_CTFL_Syllabus_v4.0.1.pdf",
          pdfFileName: "ISTQB_CTFL_Syllabus_v4.0.1.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        }
      ]
    },
    {
      id: "core-advanced",
      title: "Core Advanced",
      subtitle: "Profundización en la práctica profesional",
      color: "#328EC1",
      certifications: [
        {
          id: "ctal-ta",
          wheelLabel: "Test Analyst",
          wheelLines: ["Test", "Analyst"],
          name: "Certified Tester Advanced Level Test Analyst",
          code: "CTAL-TA",
          version: "v4.0",
          publishedYear: 2025,
          pageUrl: "https://istqb.org/certifications/certified-tester-advanced-level-test-analyst/",
          pdfUrl: "https://istqb.org/wp-content/uploads/sdm-uploads/ISTQB-CTAL-TA-Syllabus-v4.0-EN-4.pdf",
          pdfFileName: "ISTQB_CTAL-TA_Syllabus_v4.0.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ctal-tm",
          wheelLabel: "Test Management",
          wheelLines: ["Test", "Management"],
          name: "Certified Tester Advanced Level Test Management",
          code: "CTAL-TM",
          version: "v3.0",
          publishedYear: 2024,
          pageUrl: "https://istqb.org/certifications/certified-tester-advanced-level-test-management-ctal-tm-v3-0/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2024/11/ISTQB_CTAL-TM_Syllabus_v3.0_zKjKsaN.pdf",
          pdfFileName: "ISTQB_CTAL-TM_Syllabus_v3.0.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ctal-tta",
          wheelLabel: "Technical Test Analyst",
          wheelLines: ["Technical Test", "Analyst"],
          name: "Certified Tester Advanced Level Technical Test Analyst",
          code: "CTAL-TTA",
          version: "v4.0",
          publishedYear: 2021,
          pageUrl: "https://istqb.org/certifications/certified-tester-advanced-level-technical-test-analyst-ctal-tta/",
          pdfUrl: "https://istqb.org/?download_id=3463&sdm_process_download=1",
          pdfFileName: "ISTQB_CTAL-TTA_Syllabus_v4.0.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ctal-tae",
          wheelLabel: "Automation Engineering",
          wheelLines: ["Automation", "Engineering"],
          name: "Certified Tester Advanced Level Test Automation Engineering",
          code: "CTAL-TAE",
          version: "v2.0",
          publishedYear: 2024,
          pageUrl: "https://istqb.org/certifications/certified-tester-advanced-level-test-automation-engineering-ctal-tae-v2-0/",
          pdfUrl: "https://istqb.org/?download_id=3435&sdm_process_download=1",
          pdfFileName: "ISTQB_CTAL-TAE_Syllabus_v2.0.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ctal-at",
          wheelLabel: "Agile Tester",
          wheelLines: ["Agile", "Tester"],
          name: "Certified Tester Advanced Level Agile Tester",
          code: "CTAL-AT",
          version: "v2.0",
          publishedYear: 2026,
          pageUrl: "https://istqb.org/certifications/certified-tester-advanced-level-agile-tester-ctal-at/",
          pdfUrl: "https://istqb.org/?download_id=9324&sdm_process_download=1",
          pdfFileName: "ISTQB_CTAL-AT_Syllabus_v2.0.pdf",
          localPdf: null,
          status: "Vigente · nuevo en 2026",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        }
      ]
    },
    {
      id: "core-expert",
      title: "Core Expert",
      subtitle: "Liderazgo y mejora organizacional",
      color: "#3F7A86",
      certifications: [
        {
          id: "ctel-tm-otm",
          wheelLabel: "Operational Test Management",
          wheelLines: ["Operational Test", "Management"],
          name: "Expert Level Operational Test Management",
          code: "CTEL-TM-OTM",
          version: "v1.0 (2011)",
          publishedYear: 2011,
          pageUrl: "https://istqb.org/certifications/certified-tester-expert-level-test-management-operational-test-management-ctel-tm-otm/",
          pdfUrl: "https://www.istqb.org/wp-content/uploads/2024/11/ISTQB-CTEL-TM_Syllabus_v1.0_2011.pdf",
          pdfFileName: "ISTQB_CTEL-TM_Syllabus_v1.0_2011.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "Incluido: el syllabus autoriza copiar el documento completo con atribución."
        },
        {
          id: "ctel-tm-sm",
          wheelLabel: "Strategic Test Management",
          wheelLines: ["Strategic Test", "Management"],
          name: "Expert Level Strategic Test Management",
          code: "CTEL-TM-SM",
          version: "v1.0 (2011)",
          publishedYear: 2011,
          pageUrl: "https://istqb.org/certifications/certified-tester-expert-level-test-management-strategic-test-management-ctel-tm-sm/",
          pdfUrl: "https://www.istqb.org/wp-content/uploads/2024/11/ISTQB-CTEL-TM_Syllabus_v1.0_2011.pdf",
          pdfFileName: "ISTQB_CTEL-TM_Syllabus_v1.0_2011.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "Incluido: comparte syllabus con los tres módulos Expert Test Management."
        },
        {
          id: "ctel-tm-mtt",
          wheelLabel: "Managing the Test Team",
          wheelLines: ["Managing the", "Test Team"],
          name: "Expert Level Managing the Test Team",
          code: "CTEL-TM-MTT",
          version: "v1.0 (2011)",
          publishedYear: 2011,
          pageUrl: "https://istqb.org/certifications/certified-tester-expert-level-test-management-managing-the-test-team-ctel-tm-mtt/",
          pdfUrl: "https://www.istqb.org/wp-content/uploads/2024/11/ISTQB-CTEL-TM_Syllabus_v1.0_2011.pdf",
          pdfFileName: "ISTQB_CTEL-TM_Syllabus_v1.0_2011.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "Incluido: comparte syllabus con los tres módulos Expert Test Management."
        },
        {
          id: "ctel-itp-atp",
          wheelLabel: "Assessing Test Processes",
          wheelLines: ["Assessing Test", "Processes"],
          name: "Expert Level Assessing Test Processes",
          code: "CTEL-ITP-ATP",
          version: "v1.0 (2011)",
          publishedYear: 2011,
          pageUrl: "https://istqb.org/certifications/certified-tester-expert-level-assessing-test-processes-ctel-itp-atp/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2024/11/ISTQB-CTEL-ITP_Syllabus_v1.0_2011.pdf",
          pdfFileName: "ISTQB_CTEL-ITP_Syllabus_v1.0_2011.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "Incluido: el syllabus autoriza copiar el documento completo con atribución."
        },
        {
          id: "ctel-itp-itpi",
          wheelLabel: "Implementing Test Process Improvement",
          wheelLines: ["Implementing Test", "Process Improvement"],
          name: "Expert Level Implementing Test Process Improvement",
          code: "CTEL-ITP-ITPI",
          version: "v1.0 (2011)",
          publishedYear: 2011,
          pageUrl: "https://istqb.org/certifications/certified-tester-expert-level-implementing-test-process-improvement-ctel-itp-itpi/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2024/11/ISTQB-CTEL-ITP_Syllabus_v1.0_2011.pdf",
          pdfFileName: "ISTQB_CTEL-ITP_Syllabus_v1.0_2011.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "Incluido: comparte syllabus con los dos módulos Improving the Test Process."
        }
      ]
    },
    {
      id: "testing-specialist",
      title: "Testing Specialist",
      subtitle: "Tecnologías, enfoques y dominios",
      color: "#2E4B93",
      certifications: [
        {
          id: "ctal-att",
          wheelLabel: "Agile Technical",
          name: "Advanced Level Agile Technical Tester",
          code: "CTAL-ATT",
          version: "v1.1",
          publishedYear: 2019,
          pageUrl: "https://istqb.org/certifications/certified-tester-advanced-level-agile-technical-tester-ctal-att/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2024/11/ISTQB-CTAL-ATT_Syllabus_v1.1.pdf",
          pdfFileName: "ISTQB_CTAL-ATT_Syllabus_v1.1.pdf",
          localPdf: null,
          status: "En retiro · exámenes EN hasta 06/05/2027; otros idiomas hasta 06/11/2027",
          distribution: "Incluido: el syllabus autoriza copiar el documento completo con atribución."
        },
        {
          id: "ct-atlas",
          wheelLabel: "Agile at Scale",
          name: "Agile Test Leadership at Scale",
          code: "CT-ATLaS",
          version: "v2.0",
          publishedYear: 2023,
          pageUrl: "https://istqb.org/certifications/certified-tester-agile-test-leadership-at-scale-ct-atlas/",
          pdfUrl: "https://istqb.org/?download_id=3532&sdm_process_download=1",
          pdfFileName: "ISTQB_CT-ATLaS_Syllabus_v2.0.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ct-ai",
          wheelLabel: "AI Testing",
          name: "AI Testing",
          code: "CT-AI",
          version: "v2.0",
          publishedYear: 2026,
          pageUrl: "https://istqb.org/certifications/certified-tester-ai-testing-ct-ai/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2026/05/ISTQB-_CTAI_Syllabus_v2.0_Release.pdf",
          pdfFileName: "ISTQB_CT-AI_Syllabus_v2.0.pdf",
          localPdf: null,
          status: "Vigente · actualizado en 2026",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ct-genai",
          wheelLabel: "Testing with GEN AI",
          name: "Testing with Generative AI",
          code: "CT-GenAI",
          version: "v1.1",
          publishedYear: 2026,
          pageUrl: "https://istqb.org/certifications/gen-ai/",
          pdfUrl: "https://istqb.org/?download_id=6295&sdm_process_download=1",
          pdfFileName: "ISTQB_CT-GenAI_Syllabus_v1.1.pdf",
          localPdf: null,
          status: "Vigente · actualizado en 2026",
          distribution: "No incluido por criterio conservador: condiciones de la versión actual no verificadas con claridad suficiente."
        },
        {
          id: "ct-mat",
          wheelLabel: "Mobile App Testing",
          name: "Mobile Application Testing",
          code: "CT-MAT",
          version: "v1.0 (2019)",
          publishedYear: 2019,
          pageUrl: "https://istqb.org/certifications/certified-tester-mobile-application-testing-ct-mat/",
          pdfUrl: "https://www.istqb.org/wp-content/uploads/2024/11/ISTQB-CT-MAT_Syllabus_v1.0_2019.pdf",
          pdfFileName: "ISTQB_CT-MAT_Syllabus_v1.0_2019.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "Incluido: el syllabus autoriza copiar el documento completo con atribución."
        },
        {
          id: "ct-mbt",
          wheelLabel: "Model Based Testing",
          name: "Model-Based Tester",
          code: "CT-MBT",
          version: "v1.1",
          publishedYear: 2024,
          pageUrl: "https://istqb.org/certifications/certified-tester-model-based-tester-ct-mbt/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2024/11/ISTQB_CT-MBT_-_Syllabus_Version_v1.1.pdf",
          pdfFileName: "ISTQB_CT-MBT_Syllabus_v1.1.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ct-qdo",
          wheelLabel: "Quality in DevOps",
          name: "Quality in DevOps",
          code: "CT-QDO",
          version: "v1.0",
          publishedYear: 2026,
          pageUrl: "https://istqb.org/certifications/certified-tester-quality-in-devops-ct-qdo/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2026/05/ISTQB-CT-QDO-Syllabus-v1.0-EN-1.pdf",
          pdfFileName: "ISTQB_CT-QDO_Syllabus_v1.0.pdf",
          localPdf: null,
          status: "Vigente · nuevo en 2026",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ct-tas",
          wheelLabel: "Automation Strategy",
          name: "Test Automation Strategy",
          code: "CT-TAS",
          version: "v1.0",
          publishedYear: 2024,
          pageUrl: "https://istqb.org/certifications/certified-tester-test-automation-strategy-ct-tas/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2024/11/ISTQB_CT-TAS_Syllabus_v1.0.pdf",
          pdfFileName: "ISTQB_CT-TAS_Syllabus_v1.0.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ct-act",
          wheelLabel: "Acceptance",
          name: "Acceptance Testing",
          code: "CT-AcT",
          version: "v1.0 (2019)",
          publishedYear: 2019,
          pageUrl: "https://istqb.org/certifications/certified-tester-acceptance-testing-ct-act/",
          pdfUrl: "https://istqb.org/?download_id=3585&sdm_process_download=1",
          pdfFileName: "ISTQB_CT-AcT_Syllabus_v1.0_2019.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "Incluido: el syllabus autoriza copiar el documento completo con atribución."
        },
        {
          id: "ct-pt",
          wheelLabel: "Performance",
          name: "Performance Testing",
          code: "CT-PT",
          version: "v1.0 (2018)",
          publishedYear: 2018,
          pageUrl: "https://istqb.org/certifications/certified-tester-performance-testing-ct-pt/",
          pdfUrl: "https://istqb.org/?download_id=3591&sdm_process_download=1",
          pdfFileName: "ISTQB_CT-PT_Syllabus_v1.0_2018.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "Incluido: el syllabus autoriza copiar el documento completo con atribución."
        },
        {
          id: "ct-ste",
          wheelLabel: "Security Engineering",
          name: "Security Test Engineer",
          code: "CT-STE",
          version: "v1.0.1",
          publishedYear: 2025,
          pageUrl: "https://istqb.org/certifications/certified-tester-security-test-engineer/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2025/02/ISTQB_STE_v1.0.1-Syllabus.pdf",
          pdfFileName: "ISTQB_CT-STE_Syllabus_v1.0.1.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ct-sec",
          wheelLabel: "Security",
          name: "Security Tester",
          code: "CT-SEC",
          version: "v1.0 (2016)",
          publishedYear: 2016,
          pageUrl: "https://istqb.org/certifications/certified-tester-security-tester-ct-sec/",
          pdfUrl: "https://istqb.org/?download_id=3599&sdm_process_download=1",
          pdfFileName: "ISTQB_CT-SEC_Syllabus_v1.0_2016.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "Incluido: el syllabus autoriza copiar el documento completo con atribución."
        },
        {
          id: "ct-ut",
          wheelLabel: "Usability",
          name: "Usability Testing",
          code: "CT-UT",
          version: "v1.0 (2018)",
          publishedYear: 2018,
          pageUrl: "https://istqb.org/certifications/certified-tester-usability-testing-ct-ut/",
          pdfUrl: "https://istqb.org/?download_id=3607&sdm_process_download=1",
          pdfFileName: "ISTQB_CT-UT_Syllabus_v1.0_2018.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "Incluido: el syllabus autoriza copiar el documento completo con atribución."
        },
        {
          id: "ct-aut",
          wheelLabel: "Automotive",
          name: "Automotive Software Tester",
          code: "CT-AuT",
          version: "v2.1.1",
          publishedYear: 2025,
          pageUrl: "https://istqb.org/certifications/certified-tester-automotive-software-tester-ct-aut/",
          pdfUrl: "https://istqb.org/?download_id=3615&sdm_process_download=1",
          pdfFileName: "ISTQB_CT-AuT_Syllabus_v2.1.1.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ct-ft",
          wheelLabel: "Finance",
          name: "Finance Testing",
          code: "CT-FT",
          version: "v1.0",
          publishedYear: 2026,
          pageUrl: "https://istqb.org/certifications/certified-tester-finance-testing-ct-ft/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2026/05/ISTQB-CT-FT-Syllabus-Release-v1.0.pdf",
          pdfFileName: "ISTQB_CT-FT_Syllabus_v1.0.pdf",
          localPdf: null,
          status: "Vigente · nuevo en 2026",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        },
        {
          id: "ct-gt",
          wheelLabel: "Gambling",
          name: "Gambling Industry Tester",
          code: "CT-GT",
          version: "v1.0 (2019)",
          publishedYear: 2019,
          pageUrl: "https://istqb.org/certifications/certified-tester-gambling-industry-tester-ct-gt/",
          pdfUrl: "https://istqb.org/?download_id=3632&sdm_process_download=1",
          pdfFileName: "ISTQB_CT-GT_Syllabus_v1.0_2019.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "Incluido: el syllabus autoriza copiar el documento completo con atribución."
        },
        {
          id: "ct-game",
          wheelLabel: "Gaming",
          name: "Game Testing",
          code: "CT-GaMe",
          version: "v1.0.1",
          publishedYear: 2022,
          pageUrl: "https://istqb.org/certifications/certified-tester-game-testing-ct-game/",
          pdfUrl: "https://istqb.org/wp-content/uploads/2024/11/ISTQB_CT_GaMe_Syllabus_v1.0.1_LtrKuyi.pdf",
          pdfFileName: "ISTQB_CT-GaMe_Syllabus_v1.0.1.pdf",
          localPdf: null,
          status: "Vigente",
          distribution: "No incluido: requiere permiso escrito para redistribuir el documento completo."
        }
      ]
    }
  ]
};
